version: "3.8"

services:
  youtubedownloader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: youtubedownloader
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_USER_IDS=${TELEGRAM_USER_IDS}
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "pgrep", "-f", "youtubedownloader"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s
